language: node_js
sudo: false
node_js:
  - '6'
  - '5'
  - '4'
  - '0.12'
before_install:
  - npm install -g frisby
  - npm install -g jasmine-node
  - ./generate_ssl.sh
before_script:
  - npm start &
  - sleep 5
after_script:
  - process.exit()
env:
  - NODE_ENV=testing